import { Camera, ChevronRight, Loader2, Pencil, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { trpc } from "@/api/trpc";
import { MigrationCheckPanel } from "@/components/migration/MigrationCheckPanel";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { formatTimestampForInput, type SnapshotMeta } from "@/lib/snapshots";
import { cn } from "@/lib/utils";

function isAutoGeneratedLabel(label: string): boolean {
	const timestamp = formatTimestampForInput(new Date().toISOString());
	return label === timestamp;
}

function SnapshotTimelineItem({
	snapshot,
	isSelected,
	isCompareMode,
	onSelectCompare,
	onDelete,
	onRename,
	index,
	total,
}: {
	snapshot: SnapshotMeta;
	isSelected: boolean;
	isCompareMode: boolean;
	onSelectCompare: () => void;
	onDelete: () => void;
	onRename: (newLabel: string) => void;
	index: number;
	total: number;
}) {
	const [isEditing, setIsEditing] = useState(false);
	const [editValue, setEditValue] = useState(snapshot.label);
	const [confirmDelete, setConfirmDelete] = useState(false);
	const [isHovered, setIsHovered] = useState(false);
	const inputRef = useRef<HTMLInputElement>(null);

	const isLatest = index === 0;
	const isAutoLabel = isAutoGeneratedLabel(snapshot.label);

	useEffect(() => {
		if (isEditing && inputRef.current) {
			inputRef.current.focus();
			inputRef.current.select();
		}
	}, [isEditing]);

	const handleSave = () => {
		if (editValue.trim() && editValue !== snapshot.label) {
			onRename(editValue.trim());
		} else {
			setEditValue(snapshot.label);
		}
		setIsEditing(false);
	};

	const handleKeyDown = (e: React.KeyboardEvent) => {
		if (e.key === "Enter") {
			handleSave();
		} else if (e.key === "Escape") {
			setEditValue(snapshot.label);
			setIsEditing(false);
		}
	};

	const handleDelete = () => {
		if (confirmDelete) {
			onDelete();
			setConfirmDelete(false);
		} else {
			setConfirmDelete(true);
			setTimeout(() => setConfirmDelete(false), 3000);
		}
	};

	return (
		<div
			className="relative flex gap-4 py-3"
			onMouseEnter={() => setIsHovered(true)}
			onMouseLeave={() => setIsHovered(false)}
		>
			<div className="flex flex-col items-center">
				<div
					className={cn(
						"relative z-10 h-2 w-2 shrink-0 rounded-full",
						isLatest ? "bg-green-500" : "bg-white/20",
					)}
				/>
				{index < total - 1 && (
					<div className="absolute top-2 h-full w-px -translate-x-px bg-white/10" />
				)}
			</div>

			<div className="min-w-0 flex-1">
				<div className="flex items-center gap-2">
					{isEditing ? (
						<Input
							ref={inputRef}
							value={editValue}
							onChange={(e) => setEditValue(e.target.value)}
							onBlur={handleSave}
							onKeyDown={handleKeyDown}
							className="h-6 text-sm"
						/>
					) : (
						<div className="flex items-center gap-2">
							<button
								type="button"
								onClick={() => setIsEditing(true)}
								className={cn(
									"text-left font-medium text-sm hover:text-primary",
									isAutoLabel && "text-muted-foreground",
								)}
							>
								{isAutoLabel ? (
									<span className="italic">(not named)</span>
								) : (
									snapshot.label
								)}
							</button>
							{isHovered && !isEditing && (
								<button
									type="button"
									onClick={() => setIsEditing(true)}
									className="text-muted-foreground hover:text-foreground"
								>
									<Pencil className="size-3" />
								</button>
							)}
						</div>
					)}
				</div>

				<p className="mt-0.5 text-muted-foreground text-xs">
					{formatTimestampForInput(snapshot.createdAt)}
				</p>

				<div className="mt-2 flex flex-wrap gap-1.5">
					<span className="rounded bg-white/5 px-2 py-0.5 text-muted-foreground text-xs">
						{snapshot.tableCount} tables
					</span>
					<span className="rounded bg-white/5 px-2 py-0.5 text-muted-foreground text-xs">
						{snapshot.policyCount} policies
					</span>
					<span className="rounded bg-white/5 px-2 py-0.5 text-muted-foreground text-xs">
						{snapshot.roleCount} role{snapshot.roleCount !== 1 ? "s" : ""}
					</span>
				</div>
			</div>

			<div className="flex shrink-0 items-center gap-2">
				{isCompareMode ? (
					isSelected ? (
						<span className="rounded bg-green-500/20 px-2 py-1 text-green-400 text-xs">
							Selected ✓
						</span>
					) : (
						<Button size="sm" onClick={onSelectCompare} className="text-xs">
							Select to compare <ChevronRight className="size-3" />
						</Button>
					)
				) : (
					<Button
						variant="ghost"
						size="sm"
						onClick={onSelectCompare}
						className="text-muted-foreground text-xs hover:text-foreground"
					>
						Compare <ChevronRight className="size-3" />
					</Button>
				)}

				{!isCompareMode && (
					<button
						type="button"
						onClick={handleDelete}
						className={cn(
							"flex size-7 items-center justify-center rounded transition-colors",
							confirmDelete
								? "bg-destructive/20 text-destructive"
								: "text-muted-foreground hover:bg-destructive/10 hover:text-destructive",
						)}
					>
						{confirmDelete ? (
							<X className="size-3.5" />
						) : (
							<Trash2 className="size-3.5" />
						)}
					</button>
				)}
			</div>
		</div>
	);
}

function TakeSnapshotPopover({
	onSave,
	onCancel,
	isLoading,
}: {
	onSave: (label: string) => void;
	onCancel: () => void;
	isLoading: boolean;
}) {
	const [label, setLabel] = useState(() =>
		formatTimestampForInput(new Date().toISOString()),
	);
	const inputRef = useRef<HTMLInputElement>(null);

	useEffect(() => {
		if (inputRef.current) {
			inputRef.current.focus();
			inputRef.current.select();
		}
	}, []);

	return (
		<div className="absolute top-full right-0 z-10 mt-2 w-72 rounded-lg border border-border bg-card p-3 shadow-lg">
			<div className="space-y-2">
				<label
					htmlFor="snapshot-label"
					className="font-medium text-muted-foreground text-xs"
				>
					Snapshot Label
				</label>
				<Input
					ref={inputRef}
					id="snapshot-label"
					value={label}
					onChange={(e) => setLabel(e.target.value)}
					placeholder="Enter label..."
					className="text-sm"
					disabled={isLoading}
				/>
				<div className="flex items-center justify-end gap-2 pt-1">
					<button
						type="button"
						onClick={onCancel}
						disabled={isLoading}
						className="text-muted-foreground text-xs hover:text-foreground"
					>
						Cancel
					</button>
					<Button
						size="sm"
						onClick={() => onSave(label)}
						disabled={isLoading || !label.trim()}
						className="h-7 bg-success text-success-foreground hover:bg-success/90"
					>
						{isLoading ? <Loader2 className="size-3 animate-spin" /> : "Save"}
					</Button>
				</div>
			</div>
		</div>
	);
}

export function HistoryPage() {
	const navigate = useNavigate();
	const [searchParams] = useSearchParams();
	const [showPopover, setShowPopover] = useState(false);
	const [compareModeId, setCompareModeId] = useState<string | null>(null);
	const [activeTab, setActiveTab] = useState<"snapshots" | "migration">(
		"snapshots",
	);

	const snapshotsQuery = trpc.snapshots.list.useQuery();
	const createMutation = trpc.snapshots.create.useMutation({
		onSuccess: () => {
			snapshotsQuery.refetch();
			setShowPopover(false);
		},
	});
	const deleteMutation = trpc.snapshots.delete.useMutation({
		onSuccess: () => {
			snapshotsQuery.refetch();
		},
	});

	const snapshots = useMemo(
		() => snapshotsQuery.data ?? [],
		[snapshotsQuery.data],
	);

	const compareIdA = searchParams.get("compare");

	useEffect(() => {
		if (compareIdA) {
			setCompareModeId(compareIdA);
		}
	}, [compareIdA]);

	const handleCreate = (label: string) => {
		createMutation.mutate({ label });
	};

	const handleDelete = (id: string) => {
		deleteMutation.mutate({ id });
	};

	const handleRename = async (id: string, newLabel: string) => {
		await fetch("/api/snapshots/rename", {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ id, label: newLabel }),
		});
		snapshotsQuery.refetch();
	};

	const handleSelectCompare = (id: string) => {
		if (compareModeId === id) {
			setCompareModeId(null);
			navigate("/history", { replace: true });
		} else if (compareModeId) {
			navigate(`/history/diff?a=${compareModeId}&b=${id}`);
		} else {
			navigate(`/history?compare=${id}`, { replace: true });
			setCompareModeId(id);
		}
	};

	const compareSnapshot = snapshots.find((s) => s.id === compareModeId);
	const isCompareMode = !!compareModeId;

	if (activeTab === "migration") {
		return (
			<div className="flex h-full flex-col overflow-hidden px-4 pt-3 pb-4">
				<div className="mb-3 flex gap-1">
					<button
						type="button"
						onClick={() => setActiveTab("snapshots")}
						className={cn(
							"rounded px-2.5 py-1 font-medium text-xs transition-colors",
							activeTab === "snapshots"
								? "bg-primary/10 text-primary"
								: "text-muted-foreground hover:bg-white/5 hover:text-foreground",
						)}
					>
						Snapshots
					</button>
					<button
						type="button"
						onClick={() => setActiveTab("migration")}
						className={cn(
							"rounded px-2.5 py-1 font-medium text-xs transition-colors",
							activeTab === "migration"
								? "bg-primary/10 text-primary"
								: "text-muted-foreground hover:bg-white/5 hover:text-foreground",
						)}
					>
						Migration Check
					</button>
				</div>
				<div className="flex-1 overflow-hidden">
					<MigrationCheckPanel
						mode="embedded"
						defaultSnapshotId={compareModeId ?? undefined}
						snapshots={snapshots}
					/>
				</div>
			</div>
		);
	}

	return (
		<div className="flex h-full flex-col overflow-hidden px-4 pt-3 pb-4">
			<div className="mb-3 flex gap-1">
				<button
					type="button"
					onClick={() => setActiveTab("snapshots")}
					className={cn(
						"rounded px-2.5 py-1 font-medium text-xs transition-colors",
						activeTab === "snapshots"
							? "bg-primary/10 text-primary"
							: "text-muted-foreground hover:bg-white/5 hover:text-foreground",
					)}
				>
					Snapshots
				</button>
				<button
					type="button"
					onClick={() => setActiveTab("migration")}
					className={cn(
						"rounded px-2.5 py-1 font-medium text-xs transition-colors",
						activeTab === "migration"
							? "bg-primary/10 text-primary"
							: "text-muted-foreground hover:bg-white/5 hover:text-foreground",
					)}
				>
					Migration Check
				</button>
			</div>

			<div className="flex flex-wrap items-start justify-between gap-3">
				<div>
					<h1 className="font-semibold text-sm">Snapshots</h1>
					<p className="mt-0.5 text-muted-foreground text-xs">
						Save and compare your RLS policy state over time
					</p>
					<p className="mt-1 text-muted-foreground text-xs">
						{snapshots.length} snapshot{snapshots.length !== 1 ? "s" : ""} saved
						· stored in{" "}
						<code className="text-muted-foreground/70">.rlsmon/snapshots/</code>
					</p>
				</div>

				<div className="relative">
					<Button
						size="sm"
						onClick={() => setShowPopover(!showPopover)}
						className="bg-success text-success-foreground hover:bg-success/90"
					>
						<Camera className="mr-2 size-3.5" />
						Take Snapshot
					</Button>
					{showPopover && (
						<TakeSnapshotPopover
							onSave={handleCreate}
							onCancel={() => setShowPopover(false)}
							isLoading={createMutation.isPending}
						/>
					)}
				</div>
			</div>

			{isCompareMode && compareSnapshot && (
				<div className="mt-3 flex items-center justify-between rounded-lg border border-green-800 bg-green-950/50 px-3 py-2 text-sm">
					<div className="flex items-center gap-2">
						<span className="text-green-400">📸</span>
						<span>
							Comparing from:{" "}
							<span className="font-medium text-green-300">
								{compareSnapshot.label}
							</span>
						</span>
						<span className="text-muted-foreground">
							— now click 'Select to compare' on any other snapshot
						</span>
					</div>
					<button
						type="button"
						onClick={() => {
							setCompareModeId(null);
							navigate("/history", { replace: true });
						}}
						className="text-muted-foreground hover:text-foreground"
					>
						<X className="size-4" />
					</button>
				</div>
			)}

			{snapshotsQuery.isLoading ? (
				<div className="mt-4 space-y-4">
					{[1, 2, 3].map((i) => (
						<div key={i} className="flex gap-4 py-3">
							<div className="flex flex-col items-center">
								<div className="h-2 w-2 animate-pulse rounded-full bg-white/20" />
								{i < 2 && (
									<div className="h-full w-px animate-pulse bg-white/10" />
								)}
							</div>
							<div className="space-y-2">
								<div className="h-4 w-32 animate-pulse rounded bg-white/5" />
								<div className="h-3 w-24 animate-pulse rounded bg-white/5" />
							</div>
						</div>
					))}
				</div>
			) : snapshots.length === 0 ? (
				<div className="mt-12 flex flex-1 flex-col items-center justify-center">
					<Camera className="mb-4 size-12 text-muted-foreground/30" />
					<p className="font-medium text-muted-foreground text-sm">
						No snapshots yet
					</p>
					<p className="mt-1 text-muted-foreground text-xs">
						Take a snapshot to save your current RLS policy state
					</p>
					<Button
						size="sm"
						onClick={() => setShowPopover(true)}
						className="mt-4 bg-success text-success-foreground hover:bg-success/90"
					>
						<Camera className="mr-2 size-3.5" />
						Take Snapshot
					</Button>
				</div>
			) : (
				<div className="mt-3 flex-1 overflow-y-auto">
					{snapshots.map((snapshot, index) => (
						<SnapshotTimelineItem
							key={snapshot.id}
							snapshot={snapshot}
							isSelected={compareModeId === snapshot.id}
							isCompareMode={isCompareMode}
							onSelectCompare={() => handleSelectCompare(snapshot.id)}
							onDelete={() => handleDelete(snapshot.id)}
							onRename={(newLabel) => handleRename(snapshot.id, newLabel)}
							index={index}
							total={snapshots.length}
						/>
					))}
				</div>
			)}
		</div>
	);
}
